"""create feature snapshots table

Revision ID: d0a9087be7cc
Revises: f1fe7a7d01dc
Create Date: 2026-09-16 23:17:03.555449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a9087be7cc'
down_revision: Union[str, Sequence[str], None] = 'f1fe7a7d01dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kjpl_gold', sa.Float(), nullable=False),
    sa.Column('usdinr', sa.Float(), nullable=False),
    sa.Column('xauusd', sa.Float(), nullable=False),
    sa.Column('xagusd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_snapshots')
    # ### end Alembic commands ###
