"""add KJPL source updated timestamp

Revision ID: f83caea991af
Revises: d0a9087be7cc
Create Date: 2026-09-17 18:17:37.627754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83caea991af'
down_revision: Union[str, Sequence[str], None] = 'd0a9087be7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gold_rates', sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gold_rates', 'source_updated_at')
    # ### end Alembic commands ###
